# scale to zero is enabled by default. so, after some time, the pods of this service will be scaled to 0.
# or, you can disabled globally, through configmap.
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "email.fullname" . }}
  labels:
{{ include "email.labels" . | indent 4 }}
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
     annotations:
      autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
