apiVersion: flows.knative.dev/v1beta1
kind: Parallel
metadata:
  name: parallel
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
    spec:
      numPartitions: 10
      replicationFactor: 1
  branches:
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: email
    - subscriber:
        ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: invoice