apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "payment.fullname" . }}
  labels:
{{ include "payment.labels" . | indent 4 }}
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
     annotations:
      autoscaling.knative.dev/maxScale: "1"
      autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
