apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: bind-ecommerce
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        service.knative.dev/sinkbinding: ecommerce-sink-binding
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1beta1
      kind: Broker
      name: broker-purchase